# Generated by Django 3.2.2 on 2021-05-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_del_producto', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('categoria_producto', models.CharField(max_length=25)),
                ('sub_categoria_producto', models.CharField(max_length=25)),
                ('precio', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='instrumentos_images/', verbose_name='Imagen Principal')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_total', models.CharField(max_length=15)),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
