# Generated by Django 3.2.2 on 2021-05-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audifonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_del_producto', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=25)),
                ('precio', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bajos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_del_producto', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_de_producto', models.CharField(max_length=25)),
                ('precio', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BateriasAcusticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_del_producto', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_de_producto', models.CharField(max_length=25)),
                ('precio', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BateriasElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_del_producto', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_de_producto', models.CharField(max_length=25)),
                ('precio', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cabezales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_del_producto', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_de_producto', models.CharField(max_length=25)),
                ('precio', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_del_producto', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=25)),
                ('precio', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_del_producto', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_de_producto', models.CharField(max_length=25)),
                ('precio', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Guitarras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_del_producto', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_de_producto', models.CharField(max_length=25)),
                ('precio', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Interfaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_del_producto', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=25)),
                ('precio', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Microfonos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_del_producto', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=25)),
                ('precio', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mixers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_del_producto', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=25)),
                ('precio', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Monitores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_del_producto', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=25)),
                ('precio', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Parlantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_del_producto', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=25)),
                ('precio', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pianos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_del_producto', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_de_producto', models.CharField(max_length=25)),
                ('precio', models.CharField(max_length=10)),
            ],
        ),
    ]
