# Generated by Django 3.2.2 on 2021-05-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
