# Generated by Django 3.2.2 on 2021-05-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPro', '0004_subcategoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subcategoria',
        ),
    ]
