# Generated by Django 3.2.2 on 2021-05-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPro', '0005_delete_subcategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategoriacuerdas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoriacuerdas', models.CharField(max_length=30)),
            ],
        ),
    ]
